/* Generated By:JavaCC: Do not edit this line. ADTParserConstants.java */
package Parser;

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ADTParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int type = 5;
  /** RegularExpression Id. */
  int trueval = 6;
  /** RegularExpression Id. */
  int falseval = 7;
  /** RegularExpression Id. */
  int uinteger = 8;
  /** RegularExpression Id. */
  int identifier = 9;
  /** RegularExpression Id. */
  int OPENPAR = 10;
  /** RegularExpression Id. */
  int CLOSEPAR = 11;
  /** RegularExpression Id. */
  int PRIMSTART = 12;
  /** RegularExpression Id. */
  int stringrep = 13;
  /** RegularExpression Id. */
  int charrep = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<type>",
    "\"#t\"",
    "\"#f\"",
    "<uinteger>",
    "<identifier>",
    "\"(\"",
    "\")\"",
    "<PRIMSTART>",
    "<stringrep>",
    "<charrep>",
    "\"Signatures:\"",
    "\"Equations:\"",
    "\"ADT:\"",
    "\":\"",
    "\"->\"",
    "\"*\"",
    "\"=\"",
  };

}
